-- MySQL Script generated by MySQL Workbench
-- Fri Apr 23 01:58:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `nombre` VARCHAR(50) NOT NULL,
  `costo_pedido` DOUBLE NOT NULL,
  `costo_faltante` DOUBLE NOT NULL,
  `costo_inventario` DOUBLE NOT NULL,
  `inventario_inicial` INT NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prediccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Prediccion` (
  `nombre_producto` VARCHAR(50) NOT NULL,
  `mes` VARCHAR(20) NOT NULL,
  `demanda` INT NULL,
  INDEX `nombre_producto_idx` (`nombre_producto` ASC) VISIBLE,
  PRIMARY KEY (`mes`, `nombre_producto`),
  CONSTRAINT `nombre_producto`
    FOREIGN KEY (`nombre_producto`)
    REFERENCES `mydb`.`Producto` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Experimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Experimento` (
  `nombre_producto` VARCHAR(50) NOT NULL,
  `numero` INT NOT NULL,
  `punto_reorden` INT NULL,
  `cantidad_orden` INT NULL,
  PRIMARY KEY (`nombre_producto`, `numero`),
  CONSTRAINT `nombre_producto`
    FOREIGN KEY (`nombre_producto`)
    REFERENCES `mydb`.`Producto` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Simulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Simulacion` (
  `nombre_producto` VARCHAR(50) NOT NULL,
  `no_experimento` INT NOT NULL,
  `mes` VARCHAR(20) NOT NULL,
  `inv_inicial` INT NULL,
  `inv_final` INT NULL,
  `faltante` INT NULL,
  `orden` INT NULL,
  PRIMARY KEY (`nombre_producto`, `no_experimento`, `mes`),
  INDEX `no_experimento_idx` (`no_experimento` ASC) VISIBLE,
  INDEX `mes_idx` (`mes` ASC) VISIBLE,
  CONSTRAINT `nombre_producto`
    FOREIGN KEY (`nombre_producto`)
    REFERENCES `mydb`.`Producto` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `no_experimento`
    FOREIGN KEY (`no_experimento`)
    REFERENCES `mydb`.`Experimento` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mes`
    FOREIGN KEY (`mes`)
    REFERENCES `mydb`.`Prediccion` (`mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico` (
  `nombre_producto` VARCHAR(50) NOT NULL,
  `anio` INT NOT NULL,
  `mes` VARCHAR(20) NOT NULL,
  `demanda` INT NULL,
  PRIMARY KEY (`nombre_producto`, `anio`, `mes`),
  CONSTRAINT `nombre_producto`
    FOREIGN KEY (`nombre_producto`)
    REFERENCES `mydb`.`Producto` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
